---
kind: pipeline
name: web-scraper

steps:
  - name: publish
    image: plugins/gcr
    settings:
      registry: eu.gcr.io
      repo: moss-work/web-scraper
      tags: ${DRONE_COMMIT_SHA}
      json_key:
        from_secret: MW_PUSH_CREDS
    when:
      event: push
      branch: master
  - name: deploy
    image: mosstech/drone-gke-deployer:latest
    environment:
      GCP_PROJECT_ID:
        from_secret: MW_PROJECT
    commands:
      - ./go deploy
    when:
      event: push
      branch: master
